"""Documentation assembly from discovered repository structure.

The assembler organizes inventoried files by their actual source paths:

    volume  -> one markdown document per repository
    parts   -> top-level directories that contain inventoried files
    chapters-> nested directories with at least one inventoried file
    sections-> individual files
    lists   -> narrative summaries and gap/hmmm roll-ups

This is a filesystem-derived documentation hierarchy, not a dependency graph.
Dependency discovery may inform a future renderer, but this module does not
claim graph semantics it does not consume.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from . import boundary
from .evidence import FileEvidence
from .narrative import is_stale


@dataclass
class Section:
    path: str
    heading: str
    summary: str
    stale: bool
    hmmm: list[str] = field(default_factory=list)


@dataclass
class Chapter:
    title: str
    sections: list[Section] = field(default_factory=list)


@dataclass
class Part:
    title: str
    chapters: dict[str, Chapter] = field(default_factory=dict)


def _heading(path: str) -> str:
    return path.replace("_", " ").replace("-", " ")


def build_structure(
    evidence_list: list[FileEvidence], narratives: dict[str, dict[str, str]]
) -> dict[str, Part]:
    parts: dict[str, Part] = {}
    for ev in evidence_list:
        entry = narratives.get(ev.path)
        summary = entry.get("summary", "") if entry else ""
        stale = bool(entry) and is_stale(entry, ev.sha256)
        hmmm = list(ev.hmmm)
        if ev.marker is not None and not entry:
            hmmm.append("no narrative generated")
        section = Section(
            path=ev.path,
            heading=_heading(ev.path),
            summary=summary,
            stale=stale,
            hmmm=hmmm,
        )

        rel = Path(ev.path)
        top = rel.parts[0] if len(rel.parts) > 1 else "(root)"
        part = parts.setdefault(top, Part(title=_heading(top)))
        chapter_key = "/".join(rel.parts[1:-1]) or "(root)"
        chapter = part.chapters.setdefault(
            chapter_key, Chapter(title=_heading(chapter_key))
        )
        chapter.sections.append(section)
    return parts


def _render_section(section: Section) -> list[str]:
    lines = [f"#### {section.heading}", ""]
    if section.summary:
        lines.append(section.summary)
        lines.append("")
    if section.stale:
        lines.append("> stale: narrative evidence hash no longer matches this file")
        lines.append("")
    for h in section.hmmm:
        lines.append(f"- hmmm: {h}")
    if section.hmmm:
        lines.append("")
    lines.append(f"`{section.path}`")
    lines.append("")
    return lines


def render_markdown(
    root: Path,
    evidence_list: list[FileEvidence],
    narratives: dict[str, dict[str, str]],
) -> str:
    parts = build_structure(evidence_list, narratives)
    lines = [
        "# Repository examination",
        "",
        f"Repository: `{root}`",
        f"Modules examined: {len(evidence_list)}",
        f"Narratives available: {len(narratives)}",
        "",
        "Generated by the pubskill-lib examiner. Narratives are descriptive",
        "evidence bound to the source hash that produced them; a `stale` marker",
        "means the source has changed since the narrative was written.",
        "",
    ]
    for part_name in sorted(parts):
        part = parts[part_name]
        lines.append(f"## Part — {part.title}")
        lines.append("")
        for chapter_key in sorted(part.chapters):
            chapter = part.chapters[chapter_key]
            lines.append(f"### Chapter — {chapter.title}")
            lines.append("")
            for section in chapter.sections:
                lines.extend(_render_section(section))
    return "\n".join(lines)


def assemble_docs(
    root: Path,
    evidence_list: list[FileEvidence],
    narratives: dict[str, dict[str, str]],
    out_dir: Path,
) -> Path:
    """Write the assembled volume and return its path."""
    root = boundary.assert_inside(root, root)
    out = boundary.assert_inside(root, out_dir)
    out.mkdir(parents=True, exist_ok=True)
    volume = out / "EXAMINER.md"
    volume.write_text(
        render_markdown(root, evidence_list, narratives), encoding="utf-8"
    )
    return volume
